[versions]
jimmer = "0.12.2"
loom = "1.18-SNAPSHOT"
minecraft = "26.3"
loader = "0.19.5"
publish = "2.2.1"
maven = "0.37.0"
jackson = "2.21.0"

[libraries]
jimmer = { module = "org.babyfish.jimmer:jimmer-sql-kotlin", version.ref = "jimmer" }
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }
fabric-loader = { module = "net.fabricmc:fabric-loader", version.ref = "loader" }
jackson = { module = "com.fasterxml.jackson.module:jackson-module-kotlin", version.ref = "jackson" }

[plugins]
loom = { id = "net.fabricmc.fabric-loom", version.ref = "loom" }
publish = { id = "me.modmuss50.mod-publish-plugin", version.ref = "publish" }
maven = { id = "com.vanniktech.maven.publish", version.ref = "maven" }
